[build]
  publish = "dist/"
  environment = { NODE_VERSION = "16", NODE_FLAGS = "--legacy-peer-deps", NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true"}
  command = "npm run build"

[functions]
  directory = "netlify/functions/"
  included_files = ["**/*.ejs", ".env"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"